libs = -lSDL -lSDL_image -lGL -lGLU -lc2d2

comp = g++

all : scroll rotacao

scroll :
	g++ scroll.cpp -o scroll -lSDL -lSDL_image -lGL -lGLU -lc2d2
rotacao :
	g++ rotacao.cpp -o rotacao -lSDL -lSDL_image -lGL -lGLU -lc2d2

clean :
	rm scroll rotacao
